### ISSUE TITLE
Deno support request

### ISSUE THREAD

**Issue by cxumol** [fengkx/jieba-wasm#2]
```js
import { cut } from "https://cdn.skypack.dev/jieba-wasm?dts";
console.log(await cut("我來到北京清華大學"));
```
save it as `jieba-wasm.deno.js`, and run `deno --unstable run -A jieba-wasm.deno.js`

returns

```
Download https://cdn.skypack.dev/jieba-wasm?dts
Download https://cdn.skypack.dev/-/jieba-wasm@v0.0.2-9shvs7DtdzO6wlyEKmSp/dist=es2019,mode=imports/optimized/jieba-wasm.js
Download https://cdn.skypack.dev/-/jieba-wasm@v0.0.2-9shvs7DtdzO6wlyEKmSp/dist=es2019,mode=types/index.d.ts
error: Uncaught TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
    wasm.__wbindgen_add_to_stack_pointer(16);
         ^
    at cut (https://cdn.skypack.dev/-/jieba-wasm@v0.0.2-9shvs7DtdzO6wlyEKmSp/dist=es2019,mode=imports/optimized/jieba-wasm.js:173:10)
    at file:///C:/jieba-wasm.deno.js:2:19
```

Note: the CDN "skypack.dev" used in the example converts npm package into a Deno-compatible format (or at least they claim they can)

**Comment by fengkx** [comment]
`import * as jieba from 'npm:jieba-wasm/pkg/deno/jieba_rs_wasm.js'`  is avaiable
